FROM docker.io/library/ubuntu:22.04

LABEL maintainer="Fabian Böhm <fabian.bohm@hpe.com>"
ARG NB_USER="sst"
ARG NB_UID="1000"
ARG NB_GID="100"

USER root

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --yes && apt-get upgrade --yes &&\
        apt-get install --yes\
        git\
        wget\
        gcc g++ gdb\
        make autoconf\
        libtool libtool-bin\
        mpich libopenmpi-dev openmpi-bin


RUN apt-get install --yes python2 python3 python3-dev python3-pip python-is-python3

RUN pip install cmake==3.29

RUN apt-get install --yes curl

ENV SHELL=/bin/bash \
        NB_USER="${NB_USER}" \
        NB_UID=${NB_UID} \
        NB_GID=${NB_GID}

ENV HOME=/home/${NB_USER}\
        MPIHOME=$HOME/local/packages/OpenMPI-5.0.3

# Copy a script that we will use to correct permissions after running certain commands
COPY fix-permissions /usr/local/bin/fix-permissions
RUN chmod a+rx /usr/local/bin/fix-permissions

# Enable prompt color in the skeleton .bashrc before creating the default NB_USER
# hadolint ignore=SC2016
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc && \
        # Add call to conda init script see https://stackoverflow.com/a/58081608/4413446
        echo 'eval "$(command conda shell.bash hook 2> /dev/null)"' >> /etc/skel/.bashrc

# Create NB_USER with name jovyan user with UID=1000 and in the 'users' group
# and make sure these dirs are writable by the `users` group.
RUN useradd -l -m -s /bin/bash -N -u "${NB_UID}" "${NB_USER}" && \
        chown "${NB_USER}:${NB_GID}" "${HOME}" && \
        chmod g+w /etc/passwd 


RUN mkdir -p $HOME/scratch/src &&\
        mkdir -p $HOME/local/packages\
        && mkdir -p $HOME/scratch/src/certs 

RUN wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip \
        && gunzip /usr/local/bin/ninja.gz\
        && chmod a+x /usr/local/bin/ninja

#install DRAMsim3
RUN cd $HOME/scratch/src \
        && wget --no-check-certificate https://github.com/umd-memsys/DRAMsim3/archive/refs/tags/1.0.0.tar.gz \
        && tar xfz 1.0.0.tar.gz\
        && cd DRAMsim3-1.0.0\
        && export DRAMSIM3_HOME=$HOME/local/packages/dramsim3\
        && mkdir build\
        && cd build\
        && echo $(ls /usr/share)\
        && echo $(cmake --version)\
        && cmake ..\
        && make -j4\
        && cd ..\
        && cp -r . $DRAMSIM3_HOME

#install openMPI
RUN cd $HOME/scratch/src \
        && wget --no-check-certificate https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.3.tar.gz \
        && tar xfz openmpi-5.0.3.tar.gz\
        && cd openmpi-5.0.3\
        && ./configure --prefix=$MPIHOME\
        && make all install

#set PATH variables
ENV PATH=$MPIHOME/bin:$PATH\
        MPICC=mpicc\
        MPICXX=mpicxx\
        PMIX_MCA_gds=hash\
        LD_LIBRARY_PATH=$MPIHOME/lib:$LD_LIBRARY_PATH\
        DYLD_LIBRARY_PATH=$MPIHOME/lib:$DYLD_LIBRARY_PATH\
        MANPATH=$MPIHOME/share/man:$DYLD_LIBRARY_PATH\
        SST_CORE_HOME=$HOME/local/sstcore-15.0.0\
        SST_CORE_ROOT=$HOME/scratch/src/sstcore-15.0.0\
        SST_ELEMENTS_HOME=$HOME/local/sstelements-15.0.0\
        SST_ELEMENTS_ROOT=$HOME/scratch/src/sst-elements-library-15.0.0\
        DRAMSIM3_HOME=$HOME/local/packages/dramsim3

#install SST-core
RUN cd $HOME/scratch/src \
        && wget https://github.com/sstsimulator/sst-core/releases/download/v15.0.0_Final/sstcore-15.0.0.tar.gz\
        && tar xfz sstcore-15.0.0.tar.gz\
        && cd sst-core\
        && ./configure --prefix=$SST_CORE_HOME\
        && make all -j8\
        && make install -j8

ENV PATH=$SST_CORE_HOME/bin:$PATH

#install SST-elements
RUN cd $HOME/scratch/src \
        && wget https://github.com/sstsimulator/sst-elements/releases/download/v15.0.0_Final/sstelements-15.0.0.tar.gz \
        && tar xfz sstelements-15.0.0.tar.gz \
        && cd sst-elements \ 
        && ./configure --prefix=$SST_ELEMENTS_HOME --with-sst-core=$SST_CORE_HOME --with-dramsim3=$DRAMSIM3_HOME\
        && make all -j8 \
        && make install -j8

ENV PATH=$SST_ELEMENTS_HOME/bin:$PATH

RUN apt update

RUN apt-get install --yes gpg

#install gosu
RUN wget -O /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" \
        && wget -O /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture).asc" \
        && rm /usr/local/bin/gosu.asc \
        && chmod +x /usr/local/bin/gosu

RUN apt-get install --yes libboost-dev

RUN apt-get install --yes ca-certificates

RUN update-ca-certificates

RUN apt-get install --yes libc++-dev

RUN apt-get install --yes unzip

# Install XTensor Library
WORKDIR ${HOME}

RUN git clone --depth=1 --branch 0.8.0 --single-branch https://github.com/xtensor-stack/xtl.git

WORKDIR ${HOME}/xtl
RUN mkdir build
WORKDIR ${HOME}/xtl/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..\
        && make -j8\
        && make install -j8

WORKDIR ${HOME}
RUN wget https://github.com/xtensor-stack/xtensor/archive/refs/tags/0.26.0.zip\
        && unzip 0.26.0.zip\
        && rm 0.26.0.zip 

WORKDIR ${HOME}/xtensor-0.26.0
RUN mkdir build
WORKDIR ${HOME}/xtensor-0.26.0/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..\
        && make -j8\
        && make install -j8

# Install XTensor BLAS library
RUN apt-get update\
        && apt-get install --yes libblas-dev\
        && apt-get install --yes liblapack-dev
#
WORKDIR ${HOME}/
RUN wget https://github.com/xtensor-stack/xtensor-blas/archive/refs/tags/0.22.0.zip\
        && unzip 0.22.0.zip\
        && rm 0.22.0.zip
#
WORKDIR ${HOME}/xtensor-blas-0.22.0
RUN mkdir build
WORKDIR ${HOME}/xtensor-blas-0.22.0/build
RUN cmake = DCMAKE_INSTALL_PREFIX=/usr/local ..\
        && make -j8\
        && make install -j8
#

# install accelergy to use accelergy-cacti-plug-in
#WORKDIR ${HOME}
#RUN git clone --depth=1 https://github.com/Accelergy-Project/accelergy.git \
#        && cd accelergy \
#        && pip install .

RUN apt-get install --yes vim

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]